# Generated by Django 5.2.13 on 2026-04-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth_user_nickname_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('weekly_avg_reading_time', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
