# Generated by Django 5.2.4 on 2026-04-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('price_sales', models.IntegerField()),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=100)),
                ('customer_review_rank', models.IntegerField()),
            ],
        ),
    ]
