# Generated by Django 5.2.4 on 2026-04-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libraries_book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.TextField()),
                ('pubdate', models.DateField()),
                ('price', models.IntegerField()),
                ('adult', models.BooleanField()),
            ],
        ),
    ]
