# Generated by Django 5.2.13 on 2026-04-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TODO', '할 일'), ('DOING', '진행 중'), ('DONE', '완료')], default='TODO', max_length=5),
        ),
    ]
