# Generated by Django 5.2.13 on 2026-04-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TODO', '할 일'), ('DOING', '진행 중'), ('DONE', '완료')], default='TODO', help_text='현재 작업 상태를 선택해주세요.', max_length=5, verbose_name='상태'),
        ),
    ]
