# Generated by Django 5.2.13 on 2026-04-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, '낮음'), (2, '보통'), (3, '높음')], default=2, help_text='우선순위를 선택해주세요 (1=낮음, 2=보통, 3=높음).', verbose_name='우선순위'),
        ),
    ]
